language: d

os:
  - osx
  - linux

d:
 - ldc-1.9.0
 - ldc-1.8.0
 - ldc-1.7.0
 - ldc-1.6.0
 - ldc-1.5.0
 - ldc-1.4.0
 - ldc-1.3.0
 - ldc-1.2.0
 - dmd-beta
 - dmd-2.080.1 
 - dmd-2.079.1 
 - dmd-2.078.2
 - dmd-2.077.1
 - dmd-2.076.1
 - dmd-2.075.1
 - dmd-2.074.1

# ldc 1.2 to 1.5 don't work on Travis OSX because DUB requires too recent libcurl
matrix:
  exclude:
  - d: ldc-1.2.0
    os: osx
  - d: ldc-1.3.0
    os: osx
  - d: ldc-1.4.0
    os: osx

# HOPEFULLY TEMPORARY
# Things using the VST SDK can't build in the CI for now, disabled with the tag #VST

# Note: 32-bit x86 isn't tested for Linux
script:
#VST  - cd examples/distort; dub --compiler=${DC}; cd ../..
#VST  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd examples/distort; dub -a x86 --compiler=${DC}; cd ../..; fi
  - cd examples/ms-encode; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd examples/ms-encode; dub -a x86 --compiler=${DC}; cd ../..; fi
  - cd tools/pbr-sketch; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd tools/pbr-sketch; dub -a x86 --compiler=${DC}; cd ../..; fi
  - cd tools/dplug-build; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd tools/dplug-build; dub -a x86 --compiler=${DC}; cd ../..; fi
#VST  - cd tools/stress-plugin; dub --compiler=${DC}; cd ../..
#VST  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd tools/stress-plugin; dub -a x86 --compiler=${DC}; cd ../..; fi
#VST  - cd tools/process; dub --compiler=${DC}; cd ../..
#VST  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd tools/process; dub -a x86 --compiler=${DC}; cd ../..; fi
  - cd tools/wav-compare; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cd tools/wav-compare; dub -a x86 --compiler=${DC}; cd ../..; fi
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:client
#VST  - dub test --compiler=${DC} dplug:host
#VST  - dub test --compiler=${DC} dplug:vst
  - dub test --compiler=${DC} dplug:window
  - dub test --compiler=${DC} dplug:cocoa
  - dub test --compiler=${DC} dplug:carbon
  - dub test --compiler=${DC} dplug:au
  - dub test --compiler=${DC} dplug:pbr-widgets
  - dub test --compiler=${DC} dplug:flat-widgets
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:core ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:dsp ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:client ; fi
#VST  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:host ; fi
#VST  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:vst ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:window ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:cocoa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:carbon ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:au ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:pbr-widgets ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then dub test --compiler=${DC} -a x86 dplug:flat-widgets ; fi

