language: d

d:
 - dmd-2.068.0
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc-4.9.2
 
script:
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:gui
  - dub test --compiler=${DC} dplug:plugin
  - dub test --compiler=${DC} dplug:vst
  - dub test --compiler=${DC} dplug:quarantine
  - dub test --compiler=${DC} dplug:window

