language: d

d:
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1

script:
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:gui
  - dub test --compiler=${DC} dplug:plugin
  - dub test --compiler=${DC} dplug:vst

