language: d

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -y ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y gcc-multilib ; fi

os:
  - osx
  - linux

d:
 - ldc-beta
 - ldc-1.16.0
 - ldc-1.15.0
 - ldc-1.14.0
 - ldc-1.13.0
 - ldc-1.12.0
 - ldc-1.11.0
 - ldc-1.10.0
 - ldc-1.9.0
 - ldc-1.8.0
 - dmd-beta
 - dmd-2.087.0
 - dmd-2.086.1
 - dmd-2.085.1
 - dmd-2.084.1
 - dmd-2.083.1
 - dmd-2.082.1
 - dmd-2.081.2
 - dmd-2.080.1 
 - dmd-2.079.1 
 - dmd-2.078.2
 - gdc

matrix:
  allow_failures:
   - d: gdc
   - d: ldc-beta
   - d: dmd-beta

# uncompress encrypted VST SDK
before_install:
  - openssl aes-256-cbc -K $encrypted_00660bf0ef48_key -iv $encrypted_00660bf0ef48_iv -in secrets-for-ci.tar.enc -out secrets-for-ci.tar -d
  - tar xvf secrets-for-ci.tar

env:
  - VST2_SDK=$TRAVIS_BUILD_DIR/VST2_SDK


script:
  - cd examples/distort; dub --compiler=${DC}; cd ../..
  - cd examples/clipit; dub --compiler=${DC}; cd ../..
  - cd examples/ms-encode; dub --compiler=${DC}; cd ../..
  - cd examples/simple-mono-synth; dub --compiler=${DC}; cd ../..
  - cd examples/poly-alias-synth; dub --compiler=${DC}; cd ../..
  - cd tools/dplug-build; dub --compiler=${DC}; cd ../..
  - cd tools/stress-plugin; dub --compiler=${DC}; cd ../..
  - cd tools/process; dub --compiler=${DC}; cd ../..
  - cd tools/latency-check; dub --compiler=${DC}; cd ../..
  - cd tools/wav-compare; dub --compiler=${DC}; cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd examples/distort; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd examples/clipit; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd examples/ms-encode; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd examples/simple-mono-synth; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd examples/poly-alias-synth; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd tools/dplug-build; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd tools/stress-plugin; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd tools/process; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd tools/latency-check; dub --compiler=${DC}; cd ../.. ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; cd tools/wav-compare; dub --compiler=${DC}; cd ../.. ; fi
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:client
  - dub test --compiler=${DC} dplug:host
  - dub test --compiler=${DC} dplug:vst
  - dub test --compiler=${DC} dplug:window
  - dub test --compiler=${DC} dplug:cocoa
  - dub test --compiler=${DC} dplug:carbon
  - dub test --compiler=${DC} dplug:au
  - dub test --compiler=${DC} dplug:pbr-widgets
  - dub test --compiler=${DC} dplug:flat-widgets
  - dub test --compiler=${DC} dplug:lv2
  - dub test --compiler=${DC} dplug:vst3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:core ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:dsp ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:client ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:host ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:vst ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:window ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:cocoa ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:carbon ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:au ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:pbr-widgets ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:flat-widgets ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:lv2 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; dub test --compiler=${DC} dplug:vst3 ; fi
