language: d

d:
 - dmd   # latest
 - dmd-2.070.0-b2
 - dmd-2.070.0-b1
 - dmd-2.069.1
 - dmd-2.068.2
 - dmd-2.067.1
 - ldc-0.16.0

script:
  - dub test --compiler=${DC} dplug:core
  - dub test --compiler=${DC} dplug:dsp
  - dub test --compiler=${DC} dplug:gui
  - dub test --compiler=${DC} dplug:client
  - dub test --compiler=${DC} dplug:host
  - dub test --compiler=${DC} dplug:vst
  - dub test --compiler=${DC} dplug:window

