language: d

d:
 - dmd-2.067.0
 - dmd-2.066.1
 - ldc-0.15.1

script:
  - dub test --arch=x86 dplug:dsp
  - dub test --arch=x86 dplug:gui
  - dub test --arch=x86 dplug:plugin
  - dub test --arch=x86 dplug:vst
  - dub test --arch=x86_64 dplug:dsp
  - dub test --arch=x86_64 dplug:gui
  - dub test --arch=x86_64 dplug:plugin
  - dub test --arch=x86_64 dplug:vst

